function [Time, Pressure1, Pressure2] = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [TIME, PRESSURE1, PRESSURE2] = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as
%  column vectors.
%
%  [TIME, PRESSURE1, PRESSURE2] = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [Time, Pressure1, Pressure2] = importfile("C:\Users\Alex Witt\Documents\Engineering work\Fourth Year\4YP\Coding and Data\Bung Characterisation\bungrun_v2_11.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 18-Feb-2022 19:55:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", ","];

% Specify column names and types
opts.VariableNames = ["Time", "Pressure1", "Pressure2"];
opts.VariableTypes = ["datetime", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss.SSSSS");
opts = setvaropts(opts, ["Pressure1", "Pressure2"], "FillValue", 0);

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
Time = tbl.Time;
Pressure1 = tbl.Pressure1;
Pressure2 = tbl.Pressure2;
end